### ISSUE TITLE
모든 회원의 기수가 동일하게 나옵니다.

### ISSUE THREAD

**Issue by c0np4nn4** [KEEPER31337/Homepage-Front#116]
https://keeper.or.kr/ranking 에서 다른 유저의 프로필을 열람하면
모든 회원의 프로필 상의 `기수`가 `현재 로그인한 유저의 기수`로 추정되는 값으로 출력되는 현상을 발견했습니다.

![image](https://user-images.githubusercontent.com/49471288/161211529-e645cb59-5f62-4379-aac1-8acef36890d8.png)

---

<br />

프로필 화면은 아래의 코드를 통해 접근하는 것으로 보입니다.
https://github.com/KEEPER31337/Homepage-Front/blob/f851458c8aa6129921424b9500da4866e01e304b/src/page/Profile/Profile.jsx#L92-L109

`MyProfile.jsx` 파일과 `OtherProfile.jsx` 파일 각각에서 `기수` 값에 관한 부분을 아래에서 찾을 수 있었습니다.

<br />

### `MyProfile.jsx`

https://github.com/KEEPER31337/Homepage-Front/blob/e318f45758a79d971f3f6e829b7bf4e438867947/src/page/Profile/MyProfile.jsx#L25

https://github.com/KEEPER31337/Homepage-Front/blob/e318f45758a79d971f3f6e829b7bf4e438867947/src/page/Profile/MyProfile.jsx#L274-L281

<br />

### `OtherProfile.jsx`

https://github.com/KEEPER31337/Homepage-Front/blob/e318f45758a79d971f3f6e829b7bf4e438867947/src/page/Profile/OtherProfile.jsx#L48

https://github.com/KEEPER31337/Homepage-Front/blob/e318f45758a79d971f3f6e829b7bf4e438867947/src/page/Profile/OtherProfile.jsx#L238-L241

---

혹시 아래 두 코드의 차이 때문에 발생하는 현상일까요?

https://github.com/KEEPER31337/Homepage-Front/blob/e318f45758a79d971f3f6e829b7bf4e438867947/src/page/Profile/MyProfile.jsx#L277-L279

https://github.com/KEEPER31337/Homepage-Front/blob/e318f45758a79d971f3f6e829b7bf4e438867947/src/page/Profile/OtherProfile.jsx#L240

**Comment by jasper200207** [comment]
상대프로필에서 상대의 기수를 보여줘야 하는게 실수로 자신의 기수를 보여주도록 했네요... 수정해서 feature/profile에 푸시했습니다

**Comment by Yerin99** [comment]
해당 이슈는 클로즈 하도록 하겠습니다!
