### ISSUE TITLE
프로필 상 이메일을 수정하였으나, 변경되지 않습니다.

### ISSUE THREAD

**Issue by c0np4nn4** [KEEPER31337/Homepage-Front#120]
https://github.com/KEEPER31337/Homepage-Front/blob/8958aad9c9c3e28eada11f4a732c7349b42802cc/src/page/Profile/EditProfile.jsx#L217-L225

이 부분을 보면 성공적으로 업데이트 해주는 것 같은데
왜 프로필 상에서는 이메일이 안바뀔까요..ㅠㅠ

**Comment by c0np4nn4** [comment]
오늘 다시 확인해보니 정상적으로 변경되었습니다.
업데이트에 약간 시간이 걸리는 건 어쩔 수 없는 현상일까요??

**Comment by Yerin99** [comment]
백엔드 쪽에 문의해보겠습니다!

**Comment by Yerin99** [comment]
확인 결과 백엔드 쪽 문제가 아니라, 프론트엔드에서 로그인 시 받아왔었던 이메일 정보를 띄워줘서 그런 것 같습니다. 
프로필을 성공적으로 수정했을 시에, 정보를 새로 받아와서 렌더링 하도록 수정하겠습니다!
제보 감사합니다 ^_^
