### ISSUE TITLE
다크 모드 상에서 글자 색상 변경 제안

### ISSUE THREAD

**Issue by c0np4nn4** [KEEPER31337/Homepage-Front#121]
- 다크모드 적용 시 폰트 색상을 적절히 변경하는 것을 제안합니다. :)

- 아래 캡처에서 볼 수 있듯이 다크모드 적용 시 게시글 내용이 잘 보이지 않습니다.
![image](https://user-images.githubusercontent.com/49471288/161709506-d2a857b2-c25f-4295-a342-bc75993e396d.png)

<br />

- 개발자 도구로 확인한 결과 toastui-ui 라이브러리를 이용해 폰트 색상을 지정하고 있음을 확인했고 이 부분을 적절히 수정하면 되지 않을까 싶습니다.
![image](https://user-images.githubusercontent.com/49471288/161708899-66dbe336-b214-4cb8-812d-04f5c558f952.png)

**Comment by redundant4u** [comment]
해당 이슈 dark css를 불러오지 않아서 발생한 이슈였습니다.
골드색도 좋은데 일단 기본 dark css에서 하얀색 ```#fff```으로 되어있어서 [핫픽스](https://github.com/KEEPER31337/Homepage-Front/commit/b693a21cba9a34be4932b26713c2f2ea1bb8b508)해서 수정했습니다.
