### ISSUE TITLE
키퍼 도서 검색 페이지 UI 변경 제안

### ISSUE THREAD

**Issue by c0np4nn4** [KEEPER31337/Homepage-Front#123]
![image](https://user-images.githubusercontent.com/49471288/163352873-c874a37d-3868-437a-b904-910a70d0b15b.png)

도서 검색 페이지에서 채팅창으로의 버튼과 겹치는 문제가 있습니다.

[이전], [다음] 버튼을 도서 목록 상단으로 올리는건 어떨까요?

**Comment by zune2222** [comment]
이 부분은 채팅창버튼을 움직일 수 있게 해서 당장 급한 건 해결했었는데, 위로 이동하거나, 왼쪽으로 옮기는 방법으로 해결하겠습니다.
