### ISSUE TITLE
최초 접속 후 최근 게시물 클릭 시 접속 불가

### ISSUE THREAD

**Issue by hcyang1012** [KEEPER31337/Homepage-Front#127]
Windows 11 / MS Edge 환경입니다.

예를 들어, 아래와 같은 화면에서 비 로그인 상태로 _3월 회계부_  글을 클릭해 보면 빈 화면이 나타납니다.

![image](https://user-images.githubusercontent.com/1930776/164950299-f5ddb1d4-29a5-4f2b-9af4-27c7315fe2e7.png)

빈 화면이 나타난 상태에서 개발자 도구를 열어보면 다음과 같이 에러가 발생해 있음.

![image](https://user-images.githubusercontent.com/1930776/164950313-8e54d4ef-bc48-434c-862f-06ea5fbdfcd1.png)

그 이후 재 접속 해 보면 정상 접속 가능합니다.
최초 접속시에서만 현상이 일어나는 것 같으며, In Private 모드로 테스트 해 보면 항상 재현 가능 한 것 같습니다.

테스트 환경
![image](https://user-images.githubusercontent.com/1930776/164950288-ebad3560-db4e-4317-a2f7-2012dfdf2fb4.png)

한번 확인 부탁드립니다 
감사합니다

**Comment by goo-gy** [comment]
이후 접속에서는 비로그인으로 접속했는데 되던가요?

**Comment by hcyang1012** [comment]
비 로그인 상태이니까 로그인 하라는 메시지가 나옵니다. 이루 로그인 하면 게시글 열람이 가능합니다
