### ISSUE TITLE
다크 모드에서 글씨 색상 변경

### ISSUE THREAD

**Issue by 1004-head** [KEEPER31337/Homepage-Front#128]
자유게시판 글을 다크모드로 보는데 게시글 색상이 검은색으로 고정되어 글을 읽기가 힘듭니다 밝은 생각으로 조정이 필요 할 것 같습니다
<img width="768" alt="Screen Shot 2022-04-26 at 2 39 03 PM" src="https://user-images.githubusercontent.com/65378326/165230110-d13941d2-c830-4277-9892-7c38f7e96d37.png">

**Comment by goo-gy** [comment]
넵 이게 예전부터 발견했는데 toast-ui에서 theme 변경이 감지가 안되어서 해결하지 못하고 있네요. ㅠㅠ 
방법을 찾아보겠습니다. 감사합니다.

**Comment by redundant4u** [comment]
해당 이슈 [핫픽스](https://github.com/KEEPER31337/Homepage-Front/commit/b693a21cba9a34be4932b26713c2f2ea1bb8b508)해서 해결 완료!
