### ISSUE TITLE
게시글 안 보임 현상

### ISSUE THREAD

**Issue by hyeonsoo-kim** [KEEPER31337/Homepage-Front#131]
로그인 후 게시글에 접속하려고 하니, 게시글이  잠깐 열렸다가 보이지 않고 있습니다. 

개발자 모드에 들어가 보니...

![image](https://user-images.githubusercontent.com/18733991/166140708-54091b6e-b41c-4d3c-9f8c-c43ac674bf15.png)

이런 타입 오류가 있고... 네트워크 통신 추적해 보니..

![image](https://user-images.githubusercontent.com/18733991/166140954-2e62901c-d649-41db-8ec2-0bfe7d32fbeb.png)

컨텐츠들은 잘 넘어오는 것 같은데

떴다가 흰색 바탕으로 가려지는 것 같습니다..

**Comment by redundant4u** [comment]
해당 증상 확인했고 아마 오늘 중으로 업데이트 진행될 것 같습니다. 제보 감사합니다!

**Comment by redundant4u** [comment]
해당 증상 금일(5월 1일) 배포해서 조치 하였습니다.
