### ISSUE TITLE
테마 변경 안되는 버그

### ISSUE THREAD

**Issue by redundant4u** [KEEPER31337/Homepage-Front#192]
- 파이어폭스, 크롬으로 확인 결과, 다크 테마에서 라이트 테마로 변경 안됨
- 추정하기론 [이 작업](https://github.com/KEEPER31337/Homepage-Front/actions/runs/2684013310) 이후로 안되는걸로 예상

**Comment by publdaze** [comment]
fix : redux storage 분리 (8de4ec8526869dfa513f465bcb3d21b1018520ca)
이 부분부터 안되는 것 같습니다! @goo-gy

**Comment by shasuri** [comment]
현재는 라이트 테마에서 변경이 안되고, 게시글 내용 색이 하얀색으로 되어있어 보이지 않고 있습니다 ㅠㅠㅠㅜㅜ
![image](https://user-images.githubusercontent.com/29942514/184774416-974970a2-d80c-4a35-ba32-109ad935e215.png)

**Comment by publdaze** [comment]
테마 변경 안 되는 버그는 해결해서 배포 완료되었습니다!

게시글 들어간 후 게시글 내용이 모드를 변경해도 기존 모드로 유지되는 버그는 추후 해결할 예정입니다! (새로 [이슈](https://github.com/KEEPER31337/Homepage-Front/issues/216) 파놓았습니당!)
