### ISSUE TITLE
대댓글에 프로필 사진이 전염되는 버그

### ISSUE THREAD

**Issue by shasuri** [KEEPER31337/Homepage-Front#193]
![image](https://user-images.githubusercontent.com/29942514/180462663-2f96e32e-c539-4a60-8324-e2d413327142.png)

대댓글을 달면 댓글 원주인과 프로필 사진이 똑같게 표시됩니다..! ㄷㄷㄷㄷㄷ

**Comment by gusah009** [comment]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/26597702/181698689-ded03d82-85fa-4c11-a51d-7c0149455a6a.png">
저도 방금 막 보고 왔습니다..!!
