### ISSUE TITLE
테마 변경 후 로그인 세션 풀리는 문제

### ISSUE THREAD

**Issue by redundant4u** [KEEPER31337/Homepage-Front#242]
- 라이트 $\leftrightarrow$ 다크 테마 변경 후 새로고침을 하면 로그인 세션이 풀려서 다시 로그인 해야하는 버그

**Comment by publdaze** [comment]
🥲 확인해보겠습니다!

**Comment by publdaze** [comment]
https://github.com/KEEPER31337/Homepage-Front/issues/258 이슈에서 해결 중입니다! 이 이슈는 닫도록 하겠습니다!
