### ISSUE TITLE
삭제된 댓글 안보이게 하거나 수정할 수 있게 할 수 없을까여

### ISSUE THREAD

**Issue by lcy8047** [KEEPER31337/Homepage-Front#254]
![Screenshot from 2022-10-12 13-15-04](https://user-images.githubusercontent.com/35690965/195406990-98c72da6-8227-43f5-9240-4f4b8098f472.png)
댓글을 삭제했더니 댓글 목록에서 아예 없어지는게 아니라 삭제된 댓글입니다 처리가 되던데, 마크다운되는지 테스트 해보려다가 두 개나 더 달아버렸습니다 ㅠㅠ
댓글이 삭제 밖에 안되던데 수정이나 목록에서 아예 제거하는 건 안될까요 삭제된 거로 남겨두는 거는 의도하신 건가요?

+ 그리고 탈퇴회원이라고 표기되어 있어서 처음에 볼 때는 댓글 쓴 분이 탈퇴된 건가? 하고 좀 헷갈리는 부분도 있었습니다. 이 부분도 수정해주시면 감사하겠습니다.

**Comment by shasuri** [comment]
> 삭제된 거로 남겨두는 거는 의도하신 건가요?

삭제된 것으로 남겨둔 것은 의도된 것입니다!(댓글한정)
댓글이 아예 없어지면 내용이 여전히 있는 대댓글도 전부 날아가기 때문입니다.
에브리타임 같은 커뮤니티에서도 삭제된 메세지임을 명시적으로 표시하는 것으로 알고 있어요.

> 댓글이 삭제 밖에 안되던데 수정이나...

마찬가지로 에타에서도 수정을 막아놓은것으로 알고있습니다.
댓글의 내용이 전혀 다르게 변하면 이미 작성한 대댓글이 다르게 해석될 여지가 있어 그런거 같네요.
그러나, 이 경우는 운영 정책에 따라 변화를 줄 여지가 있어보입니다. 개발진 투표나 리더방에서 대화로 결정해야할 것 같아요.

> 그리고 탈퇴회원이라고 표기되어 있어서 처음에 볼 때는 댓글 쓴 분이 탈퇴된 건가? 하고 좀 헷갈리는 부분도 있었습니다. 이 
부분도 수정해주시면 감사하겠습니다.

이건 확실히 의도치 않은 버그 같네요...

**Comment by lcy8047** [comment]
그러면 혹시 회원이 탈퇴되면 그 회원이 쓴 게시글이나 댓글은 남아 있나요? 만약 삭제된다면, 기존회원이 삭제한건지, 탈퇴되어서 삭제된건지 구분해야 할 거 같은데 구현할 때 귀찮으시겠네요 ㄷ

**Comment by shasuri** [comment]
> 그러면 혹시 회원이 탈퇴되면 그 회원이 쓴 게시글이나 댓글은 남아 있나요? 
네, 내용은 남아있습니다!
