### ISSUE TITLE
게시글 썸네일 업로드 안되는 버그

### ISSUE THREAD

**Issue by redundant4u** [KEEPER31337/Homepage-Front#255]
- 게시글 작성 후 수정하는데 썸네일 사진을 올릴 수가 없습니다!
- 버그 시연 영상
![Oct-19-2022 12-32-06](https://user-images.githubusercontent.com/38307839/196591411-fe8285be-bc97-48a5-890e-3d70a12dc61c.gif)

**Comment by publdaze** [comment]
썸네일 사진은 클릭으로는 업로드 할 수 있는 기능이 없고 드래그앤드랍으로만 가능하다고 합니다! `드래그 해주세요`라는 문구 추가하였습니다!
