### ISSUE TITLE
CTF 문제 파일 다운로드 버튼 영역 버그

### ISSUE THREAD

**Issue by hyuunnn** [KEEPER31337/Homepage-Front#313]
* 버튼이 아닌 주변 영역을 눌러도 파일 다운로드가 됩니다.
![image](https://user-images.githubusercontent.com/15611739/205452114-dd1c9500-0972-45c8-8273-a752f26ccb81.png)

**Comment by publdaze** [comment]
제보 감사드립니다! 수정해서 올려두겠습니다!
