### ISSUE TITLE
썸네일 사진이 변경되는 버그

### ISSUE THREAD

**Issue by hyuunnn** [KEEPER31337/Homepage-Front#319]
![image](https://user-images.githubusercontent.com/15611739/207615840-7de73b88-5399-467d-aa82-8ceac12ba20f.png)
파일을 첨부하여 게시글을 수정하면 썸네일이 바뀌는 버그가 존재합니다.

<img width="256" alt="image" src="https://user-images.githubusercontent.com/15611739/207616220-23f05841-f12b-4d3e-b5ba-2392f36f4c70.png">
https://keeper.or.kr/v1/util/thumbnail/2에서 https://keeper.or.kr/v1/util/thumbnail/137 으로 변경됩니다.

**Comment by publdaze** [comment]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/78250089/227135890-b742c75e-c565-4dda-b130-eeb2a93a81f4.png">

스터디 페이지 수정에도 동일한 버그 발생하는 것 같네요.

**Comment by publdaze** [comment]
게시글 수정 시에 썸네일이 기존에 있던 썸네일을 동일한 Id 그대로 사용하는 형태가 아닌
기존 썸네일의 파일 정보를 가져와 새로 저장하여 다른 id를 가지게 되는 형태로 구현되어 있는 걸로 파악되었습니다.

그래서 썸네일 id가 바뀌는 건 문제가 없다고 볼 수 있으나,
기존 썸네일의 파일 정보를 가져올 때 기대했던 파일 정보와 형식이 다르게 가져와져 썸네일 정보를 읽지 못하는 이유로
문의 주신 형태의 대체 텍스트로 조회가 되고 있습니다.

빠른 시일 내로 해당 버그 해결 후 안내드리겠습니다.

담당자 : @gusah009, @publdaze

**Comment by publdaze** [comment]
게시판 수정 및 썸네일 변경 관련 이슈 해결 완료되어 해당 이슈는 Close하겠습니다.
스터디 페이지 수정 관련해서는 추가적으로 API 변경할 부분이 있어서 별도의 이슈로 열어두었습니다.
- #339
