### ISSUE TITLE
CTF 다른 시간대에서 오답시 재 제출 시간 오류

### ISSUE THREAD

**Issue by lcy8047** [KEEPER31337/Homepage-Front#329]
여기 미국동부시간대를 사용하는데요 14시간 차이가 나걸랑요? 딱 기다려야하는 시간이 14시간 5초 인거 같더라고요?
`(new Date().getTime() - new Date(lastTryTime).getTime()) / 1000;`
프론트에서 이렇게 구현되어 있던데 new Date() 하면 사용자 PC의 현지 시간으로 설정되는 것 같습니다.
lastTryTime은 서버시간으로 구현되어 있는 것 같은데,
1. 현재 서버시간을 받아오는 API가 있으면 서버시간을 받아와서 처리하거나
2. 아예 lastTryTime을 저장할 때 현지 시간으로 저장하거나
3. 접속한 유저의 시간대를 알 수 있으면 시간대를 알아내서 보정하거나 ( [여기](https://hianna.tistory.com/451) 나온 것 처럼 하면 될 거 같습니다?? )

셋 중 하나로 하면 해결될 것 같습니다.

참고로 저는 아래처럼 나옵니다
```
> date = new Date();
Date Tue Dec 27 2022 20:24:03 GMT-0500 (Eastern Standard Time)

> timezone = date.getTimezoneOffset()
300 
```
그래서 3번 방법대로 하면,
```
kst = new Date(new Date().toLocaleString('en', {timeZone: 'Asia/Seoul'}))
const timeDiff = (kst.getTime() - new Date(lastTryTime).getTime()) / 1000;
```

이렇게 수정하면 되지 않을까요?

**Comment by publdaze** [comment]
아마 3번 방법 다양한 방식으로 시도해봤던 것 같은데 다 실패해서...! 🥲
이번 학기 CTF 전까지는 해결해두겠습니다!

**Comment by publdaze** [comment]
@lcy8047 제안해주신 방법으로 해결하였습니다! (이전에 시도해봤을 때는 왜 안 됐었는 지 모르겠네요..ㅎㅎ) 감사합니다!! 👍👍
