### ISSUE TITLE
게시글 수정이 안됩니다.

### ISSUE THREAD

**Issue by shkisme** [KEEPER31337/Homepage-Front#332]
### 버그 설명 (필수)
게시글을 수정하려고 하니 수정이 안됩니다 ㅜㅜ... 라는 연락이 최근 저에게 자주 옵니다 😂
대부분 게시글 수정이 안되서 게시글 삭제하고 다시 올리시고 있는 것 같습니다.

### 버그 재현 방법 (필수)
게시글 수정 -> 수정 -> 수정하기 버튼 클릭하면 게시물 수정 실패! 라고 뜹니다.

### 의도한 동작
수정이 성공적으로 되어야 합니다.

### 스크린샷
![image](https://user-images.githubusercontent.com/92802207/227422075-d04ae89a-7aba-4c5e-9658-1e518eae290a.png)

### 데스크탑에서 발생한 경우 (아래 정보를 기입해주세요):
- OS: 맥, 윈도우 모두에서 안됩니다!
- Browser: 크롬

모바일은 안해봐서 모르겠어요!

### 추가 정보
처음에는 이것도 스터디 처럼 첨부파일, 썸네일 때문인가? 싶었는데 버그 제보 공지 올릴 때 파일이 없어도 수정이 안됨을 확인했습니다.

**Comment by publdaze** [comment]
- #319

위의 이슈와 동일한 이유로 썸네일 때문에 발생되는 버그 같은데
최초 수정 시에 바로 수정 실패가 떴는지, 아니면 두 번째 수정부터 실패가 떴는지 여부와
게시글 작성 시와 수정 시 썸네일 상태가 어땠는 지 확인 가능할까요?

**Comment by publdaze** [comment]
해결 완료되었습니다.
앞서 말씀드린대로 #319 이슈와 동일한 이유로 발생한 버그로 추정되어 관련 사항은 여기서 확인해주시고
이 이슈는 Close하겠습니다.

감사합니다.
