### ISSUE TITLE
CTF 출제자 삭제 기능 동작 안 함

### ISSUE THREAD

**Issue by 1004-head** [KEEPER31337/Homepage-Front#336]
### 버그 설명 (필수)
> CTF 페이지 대회운영 페이지에서 출제자 추가 버튼을 누르면 출제자 옆에 x 표시가 있음에도 동작하지 않아 출제자 삭제가 되지 않습니다.

### 버그 재현 방법 (필수)
> 1. CTF 페이지 접근
> 2. Admin 대회운영 탭 클릭
> 3. 출제자 추가 버튼 클릭
> 4. 출제자 이름 옆 x 표시 클릭 그러나 삭제 안 됨

### 의도한 동작
> 원래 해당 출제자가 출제자 목록에서 삭제 되어야 함.

### 추가 정보
> 다음 CTF 전(6/23)까지 빠른 수정 바랍니다.

**Comment by gusah009** [comment]
확인했습니다 완료되면 갠톡드리겠습니당

**Comment by publdaze** [comment]
리뉴얼1 프로젝트에서는 임시로 DB에 출제자 정보 제거 후 다시 추가하고 리뉴얼2 홈페이지에 해당 기능 넣는 걸로 조치하기로 하였습니다. 감사합니다.

**Comment by 1004-head** [comment]
이이잉 해조잉
