### ISSUE TITLE
주사위 게임 6회차 플레이시 정상작동하지 않습니다.

### ISSUE THREAD

**Issue by WETLION** [KEEPER31337/Homepage-Front#338]
### 버그 설명 (필수)
> 포인트 게임 중 주사위 게임을 할때 주사위를 굴릴수 있는 기회가 3번 주어져야 하나, 일일 최대 횟수인 6회차에 가면 주사위를 한번 굴린 후 추가적으로 굴리려고 하면 하루에 6회만 플레이할 수 있습니다! 라는 alert이 뜨며 주사위를 정정할수 없습니다.

### 버그 재현 방법 (필수)
> 주사위 게임 6회차를 하면 됩니다. 처음 주사위를 굴린 이후 다시 굴릴수가 없습니다.

### 의도한 동작
> 주사위를 정정할 기회가 2회 주어져야하므로, 첫 주사위 이후 새로운 값이 나와야합니다. 두번 더.

### 데스크탑에서 발생한 경우 (아래 정보를 기입해주세요):
- Windows 10 21H2
- Chrome 111

**Comment by publdaze** [comment]
아직 운영 서버에는 올라가지 않아서 현재 홈페이지 상에는 해결 안 된 상태로 보이는 게 맞습니다!
이번주 안으로 올린 후 추가 코멘트 남겨두겠습니다. 감사합니다~!

**Comment by WETLION** [comment]
앗 알겠습니다 감사합니다~~

**Comment by publdaze** [comment]
운영 서버에 올라갔습니다. 이제 정상적으로 잘 작동할 거에요!
추가적인 버그 사항 발견되면 문의주세요. 감사합니다
