### ISSUE TITLE
포인트 무한 복사, 랭킹 조작 (Overflow) 

### ISSUE THREAD

**Issue by 02ggang9** [KEEPER31337/Homepage-Front#347]
### 버그 설명 (필수)
> 어떤 문제가 있었는지 명확하고 간결하게 알려주세요.

포인트 선물 기능에 문제가 있음을 확인했습니다. 

### 버그 재현 방법 (필수)
> 어떤 순서로 접근했을때 버그가 발생했나요?

1. 상대방의 프로필에 접근 후 포인트를 보내는 Request를 확인합니다.
![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/9c8561cd-08ae-4324-a7b4-f2ef217d1b78)

2. 스스로에게 포인트를 보냅니다.
time, point, detail, presentId가 날라가는 것을 확인했는데 presentId를 밑의 팔로우 버그처럼 스스로에게 걸면 어떻게 될지 궁금했습니다. (성공했다는 메시지를 확인할 수 있습니다)
![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/6944cec1-13e9-4867-a2d6-bddbc3b3042e)

3. 포인트 내역에 스스로에게 1을 줬으니 -1을 차감하는 모습을 확인합니다.
![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/37a89fd2-29d0-4554-b84f-ed67a756fa34)

4. 음수의 값 또는 소수의 값들을 보냈을 때 어떤 동작을 하는지 확인합니다. (성공을 확인하고 포인트 내역에도 찍히는 모습)
![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/4f78e668-9eab-4b3f-92d6-6704f09a7906)

![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/34487afe-259e-456a-8a0b-726e9c11a8d5)

![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/cdb8d95d-c781-42f2-a71f-3b2c5874e24e)

5. 엄청 큰 값을 넣었을 경우에는 어떤 동작을 하는지 확인합니다.
![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/3ee02212-25cb-4f0d-b0c9-a7300687aedd)

상세한 에러 메시지를 출력해주는 것을 확인할 수 있습니다.

6. 마지막 음수 범위의 포인트로 전달
![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/521651f6-38c6-487f-ba16-bf410048eaa3)

이때 프로필에서 보이는 포인트가 깨져서 나오기 때문에 랭킹보드에서 포인트를 확인합니다.
![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/400ad85c-1012-43ad-a0e8-1883444857be)

7. 한번 더 포인트를 전달시켜서 값을 오버플로 시킬 수 있는지 확인합니다.
![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/38ffa0c9-9d40-4bbe-99ef-1c7943b55869)

![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/7c8d3a9e-d3a9-4477-a6c3-6761639147ab)

랭킹 보드에서 확인 시 오버플로 된 모습을 확인할 수 있습니다.

### 의도한 동작
> 원래 어떻게 동작되어야 하는 지 간략하게 적어주세요.

일반 회원이 음수 값을 전달할 수 없어야 합니다.

### 추가 정보
> 버그를 설명하는데 추가적인 정보가 있다면 기입해주세요.

방금 확인했는데 상대방에게 음수의 포인트를 전달해서 포인트를 흡수해 랭킹의 순위를 마음대로 조작할 수 있습니다.

![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/4368488f-5dfc-4d30-a386-f5b027dedc0f)

회장님에게 포인트를 전달하기 전
![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/b197b419-d5f1-47d9-a5c9-3418b31ecbde)

회장님에게 포인트를 전달하기 후 
![image](https://github.com/KEEPER31337/Homepage-Front/assets/105693150/9f9bd75f-8f14-438e-827d-811a03d50c1f)

**Comment by publdaze** [comment]
제보 감사드립니다!
해당 버그는 아래 이슈에서 해결되어서 Close 하겠습니다! 계속적으로 버그 발생시 재문의 부탁드립니다 감사합니다~!
https://github.com/KEEPER31337/Homepage-Front/issues/344
