### ISSUE TITLE
포인트 선물&메시지 기록 부재

### ISSUE THREAD

**Issue by redzzzi** [KEEPER31337/Homepage-Front#348]
### 버그 설명 (필수)
> 어떤 문제가 있었는지 명확하고 간결하게 알려주세요.
홍지연 회원이 여채언 회원에게 포인트를 선물하는 과정에서  포인트 란에 5000, 메시지 란에 메시지 내용을 입력 -> '선물하기' 버튼을 클릭했으나 창이 사라지거나 하는 반응이 없어 그 이후로 더블클릭 (이때 도합 15000 포인트가 전송된 듯 함.) -> 홍지연, 여채언 회원의 포인트 내역에 해당 포인트에 대한 기록이 존재하지 않음.

### 버그 재현 방법 (필수)
> 어떤 순서로 접근했을때 버그가 발생했나요?

> 1. 랭킹 창 접속
> 2. '여채언' 프로필 클릭
> 3. 포인트 선물하기 클릭
> 4. 이후는 위에서 서술한 바와 같음.

### 의도한 동작
> 원래 어떻게 동작되어야 하는 지 간략하게 적어주세요.
포인트를 주고받은 내용이 있다면, 프로필의 포인트 내역에 포인트 수량과 메시지(정보)가 기재되어야함.
ex) ![image](https://github.com/KEEPER31337/Homepage-Front/assets/127263392/e9a98a08-f1f0-43c3-9f16-7786140436f5)

### 스크린샷
> 버그가 발생한 화면을 이미지로 남겨주면 버그 파악에 용이합니다.
<img src="https://github.com/KEEPER31337/Homepage-Front/assets/127263392/d64736b8-798a-4506-a5c0-5125b44f46b8" width="250px"> 포인트 선물 전
<img src="https://github.com/KEEPER31337/Homepage-Front/assets/127263392/e0b5c532-1725-4057-a3df-50c07a75a83c" width="250px"> 포인트 선물 후
<img src="https://github.com/KEEPER31337/Homepage-Front/assets/127263392/ca4ce618-3f3b-4e45-8c26-9b8b1e485b10" width="300px"> 포인트 선물 시 입력했던 메시지 -> 이것 또한 내역에 없음

### 데스크탑에서 발생한 경우 (아래 정보를 기입해주세요):
- OS: Windows 11
- Browser: chrome

15000 포인트의 기록은 어디로 간걸까요? ㅠㅠ

**Comment by gusah009** [comment]
![image](https://github.com/KEEPER31337/Homepage-Front/assets/26597702/a17ad66a-fb58-4b7f-83f9-b215b3b0afe3)

말씀하신대로 포인트 로그에는 내역이 남지 않았습니다.

로그가 안남은 원인은 아래처럼 포인트 로그의 상세메시지에 보내신 특수문자가 인코딩이 되지 않아서인데, 이 과정에서 로그는 안남고 포인트만 전달된것으로 보입니다.

![image](https://github.com/KEEPER31337/Homepage-Front/assets/26597702/479479af-0203-45ec-bf08-c4a7c9492bcb)

포인트 자체는 전달이 된 것 같아 큰 문제는 없겠지만, 로그가 남지 않으면 포인트도 전달되지 않아야 하기 때문에 이 조치는 바로 처리해 놓겠습니다.

또 프론트에서도 서버에서 에러 메시지를 내려주면 warning을 띄워주도록 조치할 예정입니다.

제보해주셔서 감사합니다~! 👍👍

**Comment by redzzzi** [comment]
넵 감사합니다!
