### ISSUE TITLE
스터디 수정 시 이미지가 안 보이는 문제

### ISSUE THREAD

**Issue by redzzzi** [KEEPER31337/Homepage-Front#351]
### 버그 설명 (필수)
> 어떤 문제가 있었는지 명확하고 간결하게 알려주세요.
초기 스터디 관련 설정(스터디장, 스터디원, 이미지 첨부, 링크 첨부)을 한 후, 수정버튼을 사용하면 이미지가 썸네일미리보기(?)로 바뀌게 되면서 이미지를 다시 첨부해야 제대로 보입니다!

### 버그 재현 방법 (필수)
> 어떤 순서로 접근했을때 버그가 발생했나요?
1. 스터디 초기 설정을 한다.
2. 저장 후 수정하기 버튼으로 수정한다/수정 사항 없어도 수정버튼 눌러서 저장하기만 해도 버그 발생.
3. 이미지가 기존처럼 안 보이는 현상이 발생한다.

> 예시
> 1. '...'으로 이동하고
> 2. '....'을 클릭하고
> 3. '....'을 스크롤하면
> 4. 에러 발생

### 의도한 동작
> 원래 어떻게 동작되어야 하는 지 간략하게 적어주세요.
기존 초기 설정대로 이미지가 보여야 합니다!

### 스크린샷
> 버그가 발생한 화면을 이미지로 남겨주면 버그 파악에 용이합니다.
링크 수정 후
![image](https://github.com/KEEPER31337/Homepage-Front/assets/127263392/1b79486d-ba75-48da-bb36-c06668212853)
초기 모습일 때와 위 스터디 수정 후 썸네일을 삭제하고 다시 이미지를 첨부했을 때 뜨는 화면
![image](https://github.com/KEEPER31337/Homepage-Front/assets/127263392/b27f35c8-d59e-4915-b4af-433d194d27c2)

### 데스크탑에서 발생한 경우 (아래 정보를 기입해주세요):
- OS: [예시: Windows - 버전까지 적어주면 더 좋습니다!]
- Browser: [예시: chrome, safari]
윈도우, 크롬입니다.

### 모바일에서 발생한 경우 (아래 정보를 기입해주세요):
- Device: [예시: iPhone6]
- OS: [예시: iOS8.1]
- Browser: [예시: chrome, safari]

### 추가 정보
> 버그를 설명하는데 추가적인 정보가 있다면 기입해주세요.

**Comment by publdaze** [comment]
- 제보 감사드립니다! #339 이슈와 동일한 이유로 인한 버그로 보여져서 해당 이슈는 닫아두겠습니다!
- 현재 홈페이지 리뉴얼2 진행 중이라 버그 픽스 진행되지 않거나 대응이 늦어질 수 있다는 점 전달드립니다!
