### ISSUE TITLE
일부 스터디 상세 정보가 정상적으로 불러와지지 않는 문제

### ISSUE THREAD

**Issue by amaran-th** [KEEPER31337/Homepage-Front#353]
### 버그 설명 (필수)
일부 스터디의 정보가 정상적으로 불러와지지 않는 것 같습니다.

### 버그 재현 방법 (필수)
1. 스터디 페이지 접속
2. 분류를 `2023년 여름방학`으로 설정
3. 하단 3개의 스터디를 펼침
4. 스터디 상세 내용 없이 빈 내용이 출력됨
(불러와지지 않는 스터디는 그때그때 조금씩 다른 것 같습니다)

### 스크린샷
<img width="1020" alt="image" src="https://github.com/KEEPER31337/Homepage-Front/assets/81465068/87d03bd4-317f-4cec-97b9-02455755c65a">
<img width="1012" alt="image" src="https://github.com/KEEPER31337/Homepage-Front/assets/81465068/976d4ec8-9832-4fc3-bbf6-a7550d4d1156">

### 데스크탑에서 발생한 경우 (아래 정보를 기입해주세요):
- OS: Mac
- Browser: chrome

**Comment by publdaze** [comment]
버그 제보 감사합니다! 이제 버그 제보는 리뉴얼2로 받고 있어서 해당 이슈는 닫겠습니다!
https://github.com/KEEPER31337/Homepage-Front-R2/issues/839 이 이슈에서 처리할 예정이니 참고 부탁드립니다!
