### ISSUE TITLE
리뉴얼 이후 첨부파일 다운로드 관련

### ISSUE THREAD

**Issue by 04leeyoungjae** [KEEPER31337/Homepage-Front#355]
### 불편사항 설명 (필수)
> 어떤 불편사항이 있었는지 명확하고 간결하게 알려주세요.
조금전에는 버그로 올렸었는데, 개발자 도구에서 {"message":"[postId] 게시글번호: 게시글에 댓글 작성이 필요합니다."} 로 나오는 것을 보고나서 댓글을 쓰고 다운로드를 시도하니까 되긴했습니다.

### 원하는 개선 방향
> 이떤 형태로 개선되면 좋을 지 알려주세요.
다만 처음 봤을 때는 아무런 경고도 없이 그냥 다운만 안됐었는데 브라우저에서도 경고가 있으면 좋을 것 같습니다.

### 스크린샷
> 이해에 도움이 되는 이미지가 있다면 첨부해주세요.
![image](https://github.com/KEEPER31337/Homepage-Front/assets/127736867/51f4c9c9-65a7-4b30-831d-bcde2c02fbb3)

### 추가 정보
> 불편 사항을 설명하는데 더 자세한 내용이 필요하다면 여기에 기입해주세요.

**Comment by publdaze** [comment]
제보 감사드립니다!
현재 댓글 작성이 필요한 경우 토스트 메시지로 댓글 작성이 필요하다는 문구를 제공하고 있는데 해당 토스트메시지가 안 뜨는 걸까요?

https://github.com/KEEPER31337/Homepage-Front/assets/78250089/26546249-0426-465d-8027-6a69845a5640

**Comment by llddang** [comment]
네, "댓글 작성이 필요합니다." 라는 토스트 메시지가 뜨지 않습니다.

**Comment by publdaze** [comment]
<img width="1009" alt="image" src="https://github.com/KEEPER31337/Homepage-Front/assets/78250089/19d1aaf0-7d4b-4c38-87b3-cc65b5719a23">

이제 모든 게시글의 첨부파일에 파일 다운로드를 위해서 댓글 작성이 필요하다는 문구를 제공합니다.
  
토스트 메시지가 뜨지 않는 버그는 아래의 이슈에서 이어서 처리할 예정입니다.
https://github.com/KEEPER31337/Homepage-Front-R2/issues/840

감사합니다!
